const PROJECT_TEMPLATES={universal:{label:'Универсальный RP-шаблон',requiredFields:['authorNick','violatorNick','complaintType','situation','evidence'],finalText:'Прошу рассмотреть жалобу согласно регламенту проекта.',bbcodeTitle:'Жалоба'},crash:{label:'CRASH CRMP',requiredFields:['authorNick','violatorNick','complaintType','violationType','incidentDate','situation','evidence','hasC060'],finalText:'Жалоба составлена по форме проекта. Прошу принять решение.',bbcodeTitle:'Жалоба CRASH CRMP'},radmir:{label:'RADMIR RP',requiredFields:['authorNick','violatorNick','complaintType','incidentDate','situation','evidence'],finalText:'Прошу проверить эпизод и принять решение по правилам проекта.',bbcodeTitle:'Жалоба RADMIR RP'},custom:{label:'Свой шаблон',requiredFields:['authorNick','violatorNick','complaintType','situation','evidence'],finalText:'Прошу рассмотреть обращение.',bbcodeTitle:'Жалоба'}};
const VIOLATION_REWRITES={DM:'Во время игровой ситуации игрок открыл по мне огонь без веской IC-причины. Считаю, что в данной ситуации может присутствовать нарушение правил проекта, а именно DM.',MG:'В ходе ситуации игрок использовал информацию из OOC в IC-процессе. Считаю, что в данном эпизоде может присутствовать нарушение правил проекта, связанное с Metagaming.',PG:'В ходе ситуации игрок совершил действия, которые выглядят как преувеличение возможностей персонажа. Считаю, что в данном эпизоде может присутствовать нарушение правил Powergaming.',NRD:'Игрок управлял транспортом с нарушением RP-логики, что могло помешать нормальному игровому процессу. Прошу проверить ситуацию на наличие признаков NRD.',RK:'После смерти игрок вернулся к ситуации и продолжил взаимодействие, что может являться нарушением правила Revenge Kill.',SK:'Игрок совершил нападение в месте появления/возрождения, что может подпадать под правило Spawn Kill.','Оскорбление':'В ходе переписки игрок допустил некорректные высказывания в мой адрес. Прошу проверить предоставленные доказательства и принять решение согласно правилам проекта.','Неверное наказание администратора':'Считаю выданное наказание спорным. Прошу проверить действия администратора, предоставленную фиксацию и соответствие наказания регламенту проекта.',default:'В ходе игровой ситуации, по моему мнению, были нарушены правила проекта. Прошу рассмотреть предоставленные доказательства и принять решение согласно регламенту.'};
const ADMIN_REPLY_TEMPLATES={'На рассмотрении':'Ожидайте итогового решения по данной теме.','Одобрено':'Нарушение подтверждено. Игрок будет наказан согласно регламенту проекта. Тема закрыта.','Отказано':'Недостаточно оснований для выдачи наказания. Тема закрыта.','Недостаточно доказательств':'На предоставленных материалах недостаточно информации для подтверждения нарушения. Тема закрыта.','Наказание выдано верно':'Администратор предоставил фиксацию. Нарушений со стороны администратора не выявлено. Тема закрыта.','Администратор предоставил фиксацию':'По предоставленным доказательствам наказание было выдано согласно регламенту проекта. Тема закрыта.','Нарушение не подтвердилось':'Нарушение не подтвердилось. Тема закрыта.','Тема закрыта':'Тема закрыта.'};
const $=id=>document.getElementById(id); const toast=(m)=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
function getCurrentTemplate(){const key=$('projectTemplate').value;return PROJECT_TEMPLATES[key]}
function initTabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.module-panel').forEach(p=>p.classList.remove('active'));$('panel-'+b.dataset.tab).classList.add('active')})}
function updateTemplateHints(){const t=getCurrentTemplate();$('templateHints').textContent=`${t.label}: обязательные поля — ${t.requiredFields.join(', ')}.`;$('customTemplateEditor').classList.toggle('hidden',$('projectTemplate').value!=='custom');if($('projectTemplate').value==='custom')renderCustomEditor();}
function renderCustomEditor(){const host=$('customTemplateEditor');const saved=JSON.parse(localStorage.getItem('complaintBuilderCustomTemplate')||'{}');const fields=['authorNick','violatorNick','complaintType','violationType','incidentDate','situation','evidence','timecode','hasC060','extraComment'];host.innerHTML=`<h4>Свой шаблон</h4><input id="customName" placeholder="Название шаблона" value="${saved.label||''}"><input id="customTitle" placeholder="Заголовок BBCode" value="${saved.bbcodeTitle||''}"><input id="customFinal" placeholder="Финальная фраза" value="${saved.finalText||''}"><div>${fields.map(f=>`<label><input type='checkbox' class='cf' value='${f}' ${(saved.requiredFields||[]).includes(f)?'checked':''}> ${f}</label>`).join('')}</div><div class='actions'><button class='btn soft' type='button' id='saveCustom'>Сохранить свой шаблон</button><button class='btn light' type='button' id='resetCustom'>Сбросить свой шаблон</button></div>`;
$('saveCustom').onclick=()=>{const data={label:$('customName').value||'Свой шаблон',bbcodeTitle:$('customTitle').value||'Жалоба',finalText:$('customFinal').value||'Прошу рассмотреть обращение.',requiredFields:[...document.querySelectorAll('.cf:checked')].map(x=>x.value)};localStorage.setItem('complaintBuilderCustomTemplate',JSON.stringify(data));PROJECT_TEMPLATES.custom={...PROJECT_TEMPLATES.custom,...data};toast('Свой шаблон сохранён');updateTemplateHints();};
$('resetCustom').onclick=()=>{localStorage.removeItem('complaintBuilderCustomTemplate');toast('Свой шаблон сброшен');updateTemplateHints();};}
function buildStatus(){const t=getCurrentTemplate();const req=new Set(t.requiredFields);const checks=[['authorNick','Ваш ник указан','Не указан ваш ник'],['violatorNick','Ник нарушителя указан','Не указан ник нарушителя'],['complaintType','Тип жалобы выбран','Не выбран тип жалобы'],['violationType','Тип нарушения выбран','Не выбран тип нарушения'],['incidentDate','Дата указана','Дата не указана'],['situation','Описание заполнено','Не заполнено описание'],['evidence','Доказательства добавлены','Не добавлены доказательства'],['timecode','Тайм-код указан','Тайм-код не указан'],['hasC060','/c 060 отмечен','/c 060 не отмечен']];
return checks.map(([f,ok,bad])=>{const el=$(f);const filled=f==='hasC060'?el.value==='yes':!!el.value.trim();const status=filled?'ok':(req.has(f)?'bad':'warn');return {text:filled?ok:bad,status};}).concat([{text:$('situation').value.trim().length>=20?'Описание достаточно подробное':'Описание слишком короткое',status:$('situation').value.trim().length>=20?'ok':'warn'}]);}
function renderStatus(){const ul=$('statusList');ul.innerHTML='';buildStatus().forEach(s=>{const li=document.createElement('li');li.className=`status-item ${s.status}`;li.textContent=s.text;ul.append(li)});}
function calculateRisk(){const reasons=[],advice=[];const t=$('projectTemplate').value;if(!$('evidence').value.trim())reasons.push('Не указаны доказательства'),advice.push('Добавьте ссылку на видео или скриншоты');if(!$('situation').value.trim()||$('situation').value.trim().length<20)reasons.push('Описание слишком короткое'),advice.push('Сделайте описание подробнее');if(!$('violatorNick').value.trim())reasons.push('Не указан ник нарушителя');if(t==='crash'&&$('hasC060').value==='no')reasons.push('Для CRASH не отмечен /c 060'),advice.push('Проверьте наличие /c 060');const len=Number($('videoLength').value||0);if(len>60&&!$('timecode').value.trim())reasons.push('Видео длиннее 60 секунд, но тайм-код не указан'),advice.push('Укажите тайм-код нарушения');if(!$('incidentDate').value)reasons.push('Не указана дата');let level='Низкий риск',cls='risk-low';if(reasons.length>=4){level='Высокий риск';cls='risk-high';} else if(reasons.length>=2){level='Средний риск';cls='risk-medium';}return {level,cls,reasons,advice:[...new Set(advice)]};}
function renderRisk(){const r=calculateRisk();const chip=$('riskLevel');chip.className='risk-chip '+r.cls;chip.textContent=r.level;$('riskReasons').innerHTML=r.reasons.map(x=>`<li>${x}</li>`).join('')||'<li>Критичных проблем не найдено.</li>';$('riskAdvice').textContent=r.advice.join(' • ')||'Подсказка по оформлению, не официальная оценка.';}
function buildComplaintBBCode(){const t=getCurrentTemplate();const row=(n,v)=>v?`[color=#FFD166][b]${n}:[/b][/color] ${v}\n`:'';const out=`[center][size=5][color=#6EA8FF][b]${t.bbcodeTitle}[/b][/color][/size]\n\n${row('Шаблон проекта',t.label)}${row('Ваш ник',$('authorNick').value)}${row('Ник нарушителя',$('violatorNick').value)}${row('Тип жалобы',$('complaintType').value)}${row('Тип нарушения',$('violationType').value)}${row('Дата нарушения',$('incidentDate').value)}${row('Описание ситуации',$('situation').value)}${row('Доказательства',$('evidence').value)}${row('Тайм-код',$('timecode').value)}${row('/c 060',$('hasC060').value==='yes'?'Да':'Нет')}${row('Комментарий',$('extraComment').value)}\n[color=#A78BFA]${t.finalText}[/color][/center]`;return out}
function runComplaintCheck(){renderStatus();renderRisk();$('alerts').innerHTML=buildStatus().filter(x=>x.status!=='ok').map(x=>`<div class='alert warn'>${x.text}</div>`).join('')||"<div class='alert ok'>Проверка пройдена.</div>"}
function copyToClipboard(text){if(!text.trim())return;navigator.clipboard.writeText(text).then(()=>toast('BBCode скопирован'))}
function downloadTextFile(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function suggestDescription(){const t=$('violationType').value;const suggested=VIOLATION_REWRITES[t]||VIOLATION_REWRITES.default;const b=$('suggestionBox');b.innerHTML=`<p><b>Предложенное описание:</b><br>${suggested}</p><button class='btn soft mini' id='applySuggest'>Вставить предложенный текст</button> <button class='btn light mini' id='keepMine'>Оставить мой текст</button>`;b.classList.remove('hidden');$('applySuggest').onclick=()=>{$('situation').value=suggested;renderStatus();b.classList.add('hidden');};$('keepMine').onclick=()=>b.classList.add('hidden');}
function buildAdminReplyBBCode(){const type=$('adminReplyType').value;return `[center][color=#6EA8FF][b]Жалоба рассмотрена[/b][/color]\n\n[color=#FFD166][b]Проверяющий:[/b][/color] ${$('adminReviewer').value||'Не указан'}\n[color=#FFD166][b]Статус:[/b][/color] ${type}\n[color=#FFD166][b]Причина:[/b][/color] ${$('adminReason').value||'Не указана'}\n[color=#A78BFA]${$('adminComment').value||ADMIN_REPLY_TEMPLATES[type]}[/color][/center]`;}
function buildApplicationBBCode(){return `[center][size=5][color=#6EA8FF][b]${$('appType').value}[/b][/color][/size]\n\n[color=#FFD166][b]Ваш ник:[/b][/color] ${$('appNick').value}\n[color=#FFD166][b]Возраст:[/b][/color] ${$('appAge').value}\n[color=#FFD166][b]Часовой пояс:[/b][/color] ${$('appTimezone').value}\n[color=#FFD166][b]Средний онлайн:[/b][/color] ${$('appOnline').value}\n[color=#FFD166][b]Опыт:[/b][/color] ${$('appExperience').value}\n[color=#FFD166][b]Почему именно вы:[/b][/color] ${$('appWhy').value}\n[color=#FFD166][b]Сильные стороны:[/b][/color] ${$('appStrong').value}\n[color=#FFD166][b]Что хотите улучшить:[/b][/color] ${$('appImprove').value}\n[color=#FFD166][b]Связь:[/b][/color] ${$('appContact').value}\n\n[color=#A78BFA]Благодарю за рассмотрение моего заявления.[/color][/center]`;}
function drafts(){return JSON.parse(localStorage.getItem('complaintBuilderDrafts')||'[]')}
function saveDraft(){const title=$('draftTitle').value.trim();if(!title)return;const type=$('draftType').value;const content=type==='complaint'?$('output').value:type==='adminReply'?$('adminOutput').value:$('appOutput').value;const all=drafts();all.unshift({title,type,content,createdAt:new Date().toISOString()});localStorage.setItem('complaintBuilderDrafts',JSON.stringify(all));renderDrafts();toast('Черновик сохранён');}
function renderDrafts(){const host=$('draftList');host.innerHTML='';drafts().forEach((d,i)=>{const el=document.createElement('div');el.className='draft-item';el.innerHTML=`<div><b>${d.title}</b><div class='muted'>${d.type} • ${new Date(d.createdAt).toLocaleString('ru-RU')}</div></div><div><button class='btn mini soft' data-load='${i}'>Загрузить</button> <button class='btn mini light' data-del='${i}'>Удалить</button></div>`;host.append(el)});host.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const d=drafts()[b.dataset.load];if(d.type==='complaint')$('output').value=d.content;if(d.type==='adminReply')$('adminOutput').value=d.content;if(d.type==='application')$('appOutput').value=d.content;toast('Черновик загружен')});host.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const all=drafts();all.splice(Number(b.dataset.del),1);localStorage.setItem('complaintBuilderDrafts',JSON.stringify(all));renderDrafts();});}
function init(){const saved=JSON.parse(localStorage.getItem('complaintBuilderCustomTemplate')||'null');if(saved)PROJECT_TEMPLATES.custom={...PROJECT_TEMPLATES.custom,...saved};initTabs();updateTemplateHints();renderStatus();renderRisk();renderDrafts();
$('projectTemplate').onchange=()=>{updateTemplateHints();runComplaintCheck()};$('suggestBtn').onclick=suggestDescription;$('checkBtn').onclick=runComplaintCheck;$('generateBtn').onclick=()=>{$('output').value=buildComplaintBBCode();runComplaintCheck();toast('BBCode сгенерирован')};$('copyBtn').onclick=()=>copyToClipboard($('output').value);$('previewCopyBtn').onclick=()=>$('copyBtn').click();$('downloadComplaintBtn').onclick=()=>downloadTextFile('complaint-bbcode.txt',$('output').value);$('complaintForm').onreset=()=>setTimeout(()=>{ $('output').value='';$('alerts').innerHTML='';runComplaintCheck();toast('Форма очищена');},0);
['authorNick','violatorNick','complaintType','violationType','incidentDate','situation','evidence','timecode','videoLength','hasC060','extraComment'].forEach(id=>$(id).addEventListener('input',()=>{renderStatus();renderRisk();}));
$('adminGenerate').onclick=()=>{$('adminOutput').value=buildAdminReplyBBCode();toast('BBCode сгенерирован')};$('adminCopy').onclick=()=>copyToClipboard($('adminOutput').value);$('adminDownload').onclick=()=>downloadTextFile('admin-reply-bbcode.txt',$('adminOutput').value);
$('appGenerate').onclick=()=>{$('appOutput').value=buildApplicationBBCode();toast('BBCode сгенерирован')};$('appCopy').onclick=()=>copyToClipboard($('appOutput').value);$('appDownload').onclick=()=>downloadTextFile('application-bbcode.txt',$('appOutput').value);
$('saveDraftBtn').onclick=saveDraft;$('clearDraftsBtn').onclick=()=>{localStorage.removeItem('complaintBuilderDrafts');renderDrafts();};
const ob=new IntersectionObserver((e)=>e.forEach(x=>x.target.classList.toggle('visible',x.isIntersecting)),{threshold:.15});document.querySelectorAll('.reveal').forEach(el=>ob.observe(el));}
init();
